---
- name: Yum update
  yum:
    update_cache: yes

- name: Install wget and java
  yum:
    name: 
      - wget
      - java-1.8.0-openjdk.x86_64
    state: present

- name: Download nexus
  get_url:
    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /home/ec2-user/appnexus.tar.gz

- name: Unarchieve nexus
  unarchive:
    src: appnexus.tar.gz
    dest: /home/ec2-user
    remote_src: yes

- name: Rename nexus
  command: "mv /home/ec2-user/nexus-3.47.0-01 /home/ec2-user/nexus"

- name: Create nexus user
  user:
    name: nexus

- name: Change file ownership, group and permissions
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: nexus
    group: nexus
  with_items:
    - /home/ec2-user/nexus
    - /home/ec2-user/sonatype-work

- name: Run_as_nexus_user
  lineinfile:
    path: /home/ec2-user/nexus/bin/nexus.rc
    regexp: '^#run_as_user=""'
    line: run_as_user="nexus"


- name: Copy file
  template:
    src: nexus.service
    dest: /etc/systemd/system/nexus.service

- name: Enable and start service nexus
  service:
    name: nexus
    state: started
    enabled: yes